---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "sc-be-test-service"
  namespace: "default"
  labels:
    app: "sc-be-test"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "sc-be-test"
  type: "LoadBalancer"
  loadBalancerIP: ""
